"""
Tests for ExampleWorkflow tasks
Auto-generated by FlowLang Scaffolder on 2025-10-11 13:07:15

IMPORTANT: This file was generated with smart merge.
Implemented tests have been preserved.
"""

import pytest
import asyncio
import sys
from pathlib import Path

# Add parent directory to path for flow module import
sys.path.insert(0, str(Path(__file__).parent.parent))

from flow import create_task_registry
from flowlang.exceptions import NotImplementedTaskError


@pytest.fixture
def registry():
    """Fixture providing task registry"""
    return create_task_registry()


# ========================================================================
# TASK TESTS
# ========================================================================

@pytest.mark.skip(reason="Task not yet implemented")
@pytest.mark.asyncio
async def test_process_input(registry):
    """
    Test ProcessInput task
    
    This test is skipped until the task is implemented.
    
    After implementing the task:
    1. Remove the @pytest.mark.skip decorator
    2. Update this test to verify:
       - Correct output structure
       - Expected values
       - Error handling
    """
    # Get the task
    task = registry.get_task('ProcessInput')
    
    # Test inputs
    value = 'test_value'
    
    # Currently expecting NotImplementedTaskError
    with pytest.raises(NotImplementedTaskError):
        await task(value=value)
    
    # TODO: After implementing, replace above with actual assertions:
    # result = await task(value=value)
    # assert isinstance(result, dict)
    # assert "expected_key" in result
    # assert result["expected_key"] == expected_value


# ========================================================================
# INTEGRATION TESTS
# ========================================================================

def test_all_tasks_registered(registry):
    """Verify all tasks are registered"""
    expected_tasks = [
        'ProcessInput',
    ]
    
    for task in expected_tasks:
        assert registry.has_task(task), f"Task {task} not registered"


def test_implementation_progress(registry):
    """Track implementation progress"""
    from flow import get_implementation_status
    
    status = get_implementation_status()
    print(f"\nImplementation progress: {status['progress']} ({status['percentage']:.1f}%)")
    
    # This test always passes but shows progress
    assert status['total'] > 0


if __name__ == '__main__':
    pytest.main([__file__, '-v'])